version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - llm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - llm-network
    command: redis-server --appendonly yes

  llm-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-gateway
    depends_on:
      ollama:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - AUTH_ENABLED=false
      - CACHE_ENABLED=true
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_BASE_URL=http://ollama:11434
      - DEFAULT_PROVIDER=ollama
      - "PROVIDER_MODEL_MAPPING={\"ollama\": [\"llama3.2:1b\"]}"
    networks:
      - llm-network
    restart: unless-stopped

volumes:
  ollama_data:
  redis_data:

networks:
  llm-network:
    driver: bridge 